[package]
name = "p1"
version = "0.1.0"
authors = ["jjtt <3908945+jjtt@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
