[package]
name = "day6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.26.2"

[dev-dependencies]
test-case = { version = "1", features = ["hamcrest_assertions"] }
hamcrest2 = "0.3.0"
