[package]
name = "d13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
scan_fmt = "0.2.6"
json = "0.12.4"
test-case = "2.2.2"